/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Hospital_Management.Encounter;
import Hospital_Management.Patient;
import Hospital_Management.Patient_Directory;
import Hospital_Management.Person;
import Hospital_Management.Person_Directory;
import Hospital_Management.Vital_Signs;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author PRIYANSHI TANEJA
 */
public class ADD_PATIENT extends javax.swing.JPanel {

    public ArrayList<Person> filteredList = new ArrayList<>();
    Patient selectedPatient;
    Person selectedPerson;

    /**
     * Creates new form AddPatientVisit
     */
    public ADD_PATIENT() {
        initComponents();
        detailsJPanel.setVisible(false);
        filteredJList.setVisible(false);
        visitJPanel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        searchNameJField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        filteredJList = new javax.swing.JList<>();
        detailsJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addressJLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        identifierJLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        zipCodeJLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cityJLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stateJLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        communityNameJLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dobJLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mobileNoJLabel = new javax.swing.JLabel();
        addVisitJButton = new javax.swing.JButton();
        visitJPanel = new javax.swing.JPanel();
        seatsJLabel = new javax.swing.JLabel();
        respiratoryRateJField = new javax.swing.JTextField();
        seatsJLabel1 = new javax.swing.JLabel();
        heartRateJField = new javax.swing.JTextField();
        seatsJLabel2 = new javax.swing.JLabel();
        bloodPressureJField = new javax.swing.JTextField();
        seatsJLabel3 = new javax.swing.JLabel();
        ageJField = new javax.swing.JTextField();
        cardentifierJLabel = new javax.swing.JLabel();
        patientIdentifierJLabel = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setForeground(new java.awt.Color(153, 204, 255));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Select Patient:");

        searchNameJField.setBackground(new java.awt.Color(238, 238, 238));
        searchNameJField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchNameJField.setToolTipText("Click to enter your name.");
        searchNameJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        searchNameJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchNameJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchNameJFieldnameChangeHandler(evt);
            }
        });
        searchNameJField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                searchNameJFieldInputMethodTextChanged(evt);
            }
        });
        searchNameJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameJFieldActionPerformed(evt);
            }
        });
        searchNameJField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchNameJFieldKeyReleased(evt);
            }
        });

        filteredJList.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        filteredJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filteredJListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(filteredJList);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Name:");

        nameJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        nameJLabel.setText("Select Person to see details!");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Address:");

        addressJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        addressJLabel.setText("Select Person to see details!");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Enrollment Number");

        identifierJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        identifierJLabel.setText("Select Person to see details!");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Zip Code:");

        zipCodeJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        zipCodeJLabel.setText("Select Person to see details!");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("City:");

        cityJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cityJLabel.setText("Select Person to see details!");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("State:");

        stateJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        stateJLabel.setText("Select Person to see details!");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("Community Name:");

        communityNameJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        communityNameJLabel.setText("Select Person to see details!");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("DOB:");

        dobJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        dobJLabel.setText("Select Person to see details!");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setText("Email ID:");

        emailJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        emailJLabel.setText("Select Person to see details!");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setText("Mobile No.:");

        mobileNoJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        mobileNoJLabel.setText("Select Person to see details!");

        addVisitJButton.setText("Add Visit");
        addVisitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVisitJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailsJPanelLayout = new javax.swing.GroupLayout(detailsJPanel);
        detailsJPanel.setLayout(detailsJPanelLayout);
        detailsJPanelLayout.setHorizontalGroup(
            detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addVisitJButton)
                    .addComponent(nameJLabel)
                    .addComponent(addressJLabel)
                    .addComponent(identifierJLabel)
                    .addComponent(zipCodeJLabel)
                    .addComponent(cityJLabel)
                    .addComponent(stateJLabel)
                    .addComponent(communityNameJLabel)
                    .addComponent(emailJLabel)
                    .addComponent(dobJLabel)
                    .addComponent(mobileNoJLabel))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        detailsJPanelLayout.setVerticalGroup(
            detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(identifierJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameJLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressJLabel)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zipCodeJLabel)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityJLabel)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stateJLabel)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(communityNameJLabel)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dobJLabel)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailJLabel)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(mobileNoJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addVisitJButton))
        );

        seatsJLabel.setFont(new java.awt.Font("PT Sans Caption", 0, 14)); // NOI18N
        seatsJLabel.setText("Respiratory Rate (*) :");

        respiratoryRateJField.setBackground(new java.awt.Color(238, 238, 238));
        respiratoryRateJField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        respiratoryRateJField.setToolTipText("Click to enter your name.");
        respiratoryRateJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        respiratoryRateJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                respiratoryRateJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                respiratoryRateJFieldnameChangeHandler(evt);
            }
        });
        respiratoryRateJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respiratoryRateJFieldActionPerformed(evt);
            }
        });

        seatsJLabel1.setFont(new java.awt.Font("PT Sans Caption", 0, 14)); // NOI18N
        seatsJLabel1.setText("Heart Rate (*) :");

        heartRateJField.setBackground(new java.awt.Color(238, 238, 238));
        heartRateJField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        heartRateJField.setToolTipText("Click to enter your name.");
        heartRateJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        heartRateJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                heartRateJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                heartRateJFieldnameChangeHandler(evt);
            }
        });
        heartRateJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartRateJFieldActionPerformed(evt);
            }
        });

        seatsJLabel2.setFont(new java.awt.Font("PT Sans Caption", 0, 14)); // NOI18N
        seatsJLabel2.setText("Blood Pressure (*) :");

        bloodPressureJField.setBackground(new java.awt.Color(238, 238, 238));
        bloodPressureJField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        bloodPressureJField.setToolTipText("Click to enter your name.");
        bloodPressureJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        bloodPressureJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bloodPressureJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bloodPressureJFieldnameChangeHandler(evt);
            }
        });
        bloodPressureJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodPressureJFieldActionPerformed(evt);
            }
        });

        seatsJLabel3.setFont(new java.awt.Font("PT Sans Caption", 0, 14)); // NOI18N
        seatsJLabel3.setText("Age (*) :");

        ageJField.setBackground(new java.awt.Color(238, 238, 238));
        ageJField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ageJField.setToolTipText("Click to enter your name.");
        ageJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        ageJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageJFieldnameChangeHandler(evt);
            }
        });
        ageJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageJFieldActionPerformed(evt);
            }
        });

        cardentifierJLabel.setFont(new java.awt.Font("PT Sans Caption", 0, 14)); // NOI18N
        cardentifierJLabel.setText("Enrollment Number");

        patientIdentifierJLabel.setEditable(false);
        patientIdentifierJLabel.setBackground(new java.awt.Color(238, 238, 238));
        patientIdentifierJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        patientIdentifierJLabel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        patientIdentifierJLabel.setToolTipText("This is your identifier.");
        patientIdentifierJLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        patientIdentifierJLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIdentifierJLabelActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(67, 100, 100));

        jButton2.setBackground(new java.awt.Color(238, 238, 238));
        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("/minute");

        jLabel14.setText("bpm");

        jLabel15.setText("mm Hg");

        javax.swing.GroupLayout visitJPanelLayout = new javax.swing.GroupLayout(visitJPanel);
        visitJPanel.setLayout(visitJPanelLayout);
        visitJPanelLayout.setHorizontalGroup(
            visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visitJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seatsJLabel)
                    .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cardentifierJLabel)
                        .addComponent(seatsJLabel2)))
                .addGap(35, 35, 35)
                .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(patientIdentifierJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(bloodPressureJField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(respiratoryRateJField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel15))
                .addGap(33, 33, 33)
                .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(visitJPanelLayout.createSequentialGroup()
                        .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatsJLabel1)
                            .addComponent(seatsJLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(heartRateJField, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(ageJField))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, visitJPanelLayout.createSequentialGroup()
                    .addContainerGap(642, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(138, 138, 138)))
        );
        visitJPanelLayout.setVerticalGroup(
            visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visitJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seatsJLabel)
                    .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(respiratoryRateJField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(seatsJLabel1)
                        .addComponent(heartRateJField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, visitJPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ageJField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, visitJPanelLayout.createSequentialGroup()
                        .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(visitJPanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(seatsJLabel2)
                                    .addComponent(bloodPressureJField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(visitJPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(seatsJLabel3))))
                        .addGap(27, 27, 27)
                        .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cardentifierJLabel)
                            .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(patientIdentifierJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(visitJPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(visitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(visitJPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visitJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(detailsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchNameJField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(searchNameJField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(detailsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visitJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchNameJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchNameJFieldFocusGained
        if (searchNameJField.getText().equals("Enter here")) {
            searchNameJField.setText("");
        }
    }//GEN-LAST:event_searchNameJFieldFocusGained

    private void searchNameJFieldnameChangeHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchNameJFieldnameChangeHandler
        // TODO add your handling code here:
    }//GEN-LAST:event_searchNameJFieldnameChangeHandler

    private void searchNameJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchNameJFieldActionPerformed

    private void searchNameJFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_searchNameJFieldInputMethodTextChanged

    }//GEN-LAST:event_searchNameJFieldInputMethodTextChanged

    private void filteredJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filteredJListMouseClicked
        openSelectedProfile();

    }//GEN-LAST:event_filteredJListMouseClicked

    private void searchNameJFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchNameJFieldKeyReleased
        if ("".equals(searchNameJField.getText())) {
            return;
        }
        filteredList.clear();
        filteredJList.removeAll();
        detailsJPanel.setVisible(false);
        visitJPanel.setVisible(false);
        for (int i = 0; i < Person_Directory.allPeople.size(); i++) {
            Person onGoing = Person_Directory.allPeople.get(i);
            if (onGoing.name.contains(searchNameJField.getText())) {
                filteredList.add(onGoing);
            }
        }
        filteredJList.setVisible(true);
        DefaultListModel model = new DefaultListModel();

        filteredList.forEach(patient -> {
            model.addElement(patient.personId + " - " + patient.name);
        });
        filteredJList.setModel(model);
        filteredJList.setSelectedIndex(0);
    }//GEN-LAST:event_searchNameJFieldKeyReleased

    private void respiratoryRateJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_respiratoryRateJFieldFocusGained
        if (respiratoryRateJField.getText().equals("Enter here")) {
            respiratoryRateJField.setText("");
        }
    }//GEN-LAST:event_respiratoryRateJFieldFocusGained

    private void respiratoryRateJFieldnameChangeHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_respiratoryRateJFieldnameChangeHandler
        // TODO add your handling code here:
    }//GEN-LAST:event_respiratoryRateJFieldnameChangeHandler

    private void respiratoryRateJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respiratoryRateJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respiratoryRateJFieldActionPerformed

    private void heartRateJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_heartRateJFieldFocusGained
        if (heartRateJField.getText().equals("Enter here")) {
            heartRateJField.setText("");
        }
    }//GEN-LAST:event_heartRateJFieldFocusGained

    private void heartRateJFieldnameChangeHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_heartRateJFieldnameChangeHandler
        // TODO add your handling code here:
    }//GEN-LAST:event_heartRateJFieldnameChangeHandler

    private void heartRateJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartRateJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heartRateJFieldActionPerformed

    private void bloodPressureJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bloodPressureJFieldFocusGained
        if (bloodPressureJField.getText().equals("Enter here")) {
            bloodPressureJField.setText("");
        }
    }//GEN-LAST:event_bloodPressureJFieldFocusGained

    private void bloodPressureJFieldnameChangeHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bloodPressureJFieldnameChangeHandler
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodPressureJFieldnameChangeHandler

    private void bloodPressureJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodPressureJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodPressureJFieldActionPerformed

    private void ageJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageJFieldFocusGained
        if (ageJField.getText().equals("Enter here")) {
            ageJField.setText("");
        }
    }//GEN-LAST:event_ageJFieldFocusGained

    private void ageJFieldnameChangeHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageJFieldnameChangeHandler
        // TODO add your handling code here:
    }//GEN-LAST:event_ageJFieldnameChangeHandler

    private void ageJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageJFieldActionPerformed

    private void patientIdentifierJLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIdentifierJLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIdentifierJLabelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Boolean isAlreadyAPatient = isAlreadyPatient();
        String errorMessage = "";
        Vital_Signs vitals = new Vital_Signs();
        String respiratoryErrorMessage = vitals.validateRespiratoryRate(String.valueOf(this.respiratoryRateJField.getText()));
        String heartRateErrorMessage = vitals.validateHeartRate(String.valueOf(this.heartRateJField.getText()));
        String bloodPresureErrorMessage = vitals.validateBloodPressure(String.valueOf(this.bloodPressureJField.getText()));
        String ageErrorMessage = vitals.validateAge(String.valueOf(this.ageJField.getText()));

        errorMessage += respiratoryErrorMessage;
        errorMessage += heartRateErrorMessage;
        errorMessage += bloodPresureErrorMessage;
        errorMessage += ageErrorMessage;

        if (!errorMessage.equals("")) {
            JOptionPane.showMessageDialog(this, errorMessage, "Create Patient's visit", ERROR_MESSAGE);
            return;
        }
        selectedPatient.personDetails = selectedPerson;

        vitals.age = Integer.valueOf(this.ageJField.getText());
        vitals.respiratoryRate = Integer.valueOf(this.respiratoryRateJField.getText());
        vitals.heartRate = Integer.valueOf(this.heartRateJField.getText());
        vitals.bloodPressure = Integer.valueOf(this.bloodPressureJField.getText());

        Encounter encounter = new Encounter();
        encounter.findings = vitals;
        encounter.visitDate = new Date();
        selectedPatient.allVisitsHistory.encounterHistory.add(encounter);
        int getID = getPatientId();
        selectedPatient.patientIdentifier = getID;

        visitJPanel.setVisible(false);

        patientIdentifierJLabel.setText(String.valueOf(getID));

        if (!isAlreadyAPatient) {
            Patient_Directory.patientDirectory.add(selectedPatient);
        }
        restVitals();
        JOptionPane.showMessageDialog(this, "Patient's history created successfully!!", "Create Visit", INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void restVitals() {
        ageJField.setText("Enter here");
        respiratoryRateJField.setText("Enter here");
        heartRateJField.setText("Enter here");
        bloodPressureJField.setText("Enter here");
    }

    public int getPatientId() {
        int foundID = Patient_Directory.patientDirectory.size();
        for (int i = 0; i < Patient_Directory.patientDirectory.size(); i++) {
            if (Patient_Directory.patientDirectory.get(i).personDetails.personId == selectedPerson.personId) {
                System.out.println("--Already a patient");
                foundID = Patient_Directory.patientDirectory.get(i).patientIdentifier;
            }
        }
        System.out.println("new patient--");
        return foundID;
    }

    public Boolean isAlreadyPatient() {
        Boolean found = false;
        for (int i = 0; i < Patient_Directory.patientDirectory.size(); i++) {
            if (Patient_Directory.patientDirectory.get(i).personDetails.personId == selectedPerson.personId) {
                found = true;
            }
        }
        return found;
    }

    public Patient getPatient() {
        Patient found = new Patient();
        for (int i = 0; i < Patient_Directory.patientDirectory.size(); i++) {
            if (Patient_Directory.patientDirectory.get(i).personDetails.personId == selectedPerson.personId) {
                found = Patient_Directory.patientDirectory.get(i);
            }
        }
        return found;
        
    }

    private void addVisitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVisitJButtonActionPerformed
        visitJPanel.setVisible(true);
    }//GEN-LAST:event_addVisitJButtonActionPerformed

    public void openSelectedProfile() {
        int seletedPersonIndex = filteredJList.getSelectedIndex();//get the index of the selection made in the left section.
        if (seletedPersonIndex != -1) {
            selectedPerson = Person_Directory.allPeople.get(seletedPersonIndex);
            selectedPatient = getPatient();
            detailsJPanel.setVisible(true);
            identifierJLabel.setText(String.valueOf(selectedPerson.personId));
            nameJLabel.setText(String.valueOf(selectedPerson.name));
            addressJLabel.setText(String.valueOf(selectedPerson.address.address));
            zipCodeJLabel.setText(String.valueOf(selectedPerson.address.zipcode));
            cityJLabel.setText(String.valueOf(selectedPerson.city.city));
            stateJLabel.setText(String.valueOf(selectedPerson.city.state));
            communityNameJLabel.setText(String.valueOf(selectedPerson.community.communityName));
            dobJLabel.setText((String.valueOf((new SimpleDateFormat("MM/dd/yyyy", Locale.US)).format(selectedPerson.dob))));
            emailJLabel.setText(String.valueOf(selectedPerson.email));
            mobileNoJLabel.setText(String.valueOf(selectedPerson.mobileNo));
            //Patient Identifier
            patientIdentifierJLabel.setText(String.valueOf(getPatientId()));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVisitJButton;
    private javax.swing.JLabel addressJLabel;
    private javax.swing.JTextField ageJField;
    private javax.swing.JTextField bloodPressureJField;
    private javax.swing.JLabel cardentifierJLabel;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JLabel communityNameJLabel;
    private javax.swing.JPanel detailsJPanel;
    private javax.swing.JLabel dobJLabel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JList<String> filteredJList;
    private javax.swing.JTextField heartRateJField;
    private javax.swing.JLabel identifierJLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mobileNoJLabel;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField patientIdentifierJLabel;
    private javax.swing.JTextField respiratoryRateJField;
    private javax.swing.JTextField searchNameJField;
    private javax.swing.JLabel seatsJLabel;
    private javax.swing.JLabel seatsJLabel1;
    private javax.swing.JLabel seatsJLabel2;
    private javax.swing.JLabel seatsJLabel3;
    private javax.swing.JLabel stateJLabel;
    private javax.swing.JPanel visitJPanel;
    private javax.swing.JLabel zipCodeJLabel;
    // End of variables declaration//GEN-END:variables
}
