/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Hospital_Management.Appointment;
import Hospital_Management.Doctor;
import Hospital_Management.Doctor_Directory;
import Hospital_Management.Person;
import Hospital_Management.Person_Directory;
import Hospital_Management.Doctor;
import Hospital_Management.Patient_Directory;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;


/**
 *
 * @author PRIYANSHI TANEJA
 */
public class DOCTOR_VIEW extends javax.swing.JPanel {

    Doctor selectedPerson;
    /**
     * Creates new form DoctorDirectory
     */
    public DOCTOR_VIEW() {
        
        initComponents();
        
        for (int i = 0; i < Person_Directory.allPeople.size(); i++) {
            Person sel = Person_Directory.allPeople.get(i);
            System.out.println("Person directory" + sel.personId + "-" + sel.name);
        }

        jSplitPane1.setDividerLocation((int) (0.35 * (new Dimension(Toolkit.getDefaultToolkit().getScreenSize()).width - 300)));
        DefaultListModel model = new DefaultListModel();
        encounterJList.setVisible(false);
        encounterJPanel.setVisible(false);
        if (Doctor_Directory.doctorDirectory.isEmpty()) {
            encounterJList.setModel(model);
            JOptionPane.showMessageDialog(this, "People Directory Empty!", "View Details", ERROR_MESSAGE);
        } else {
            Doctor_Directory.doctorDirectory.forEach(doctor -> {
                model.addElement(doctor.doctorIdentifier + " - " + doctor.personDetails.name);
                for (int i = 0; i < doctor.allAppointmentsHistory.AppointmentHistory.size(); i++) {
                    Appointment sel = doctor.allAppointmentsHistory.AppointmentHistory.get(i);
                    System.out.println(doctor.doctorIdentifier + "Doctors directory" + sel.visitDate + "-" + sel.findings.hospitalName);
                }
            });
            encounterJList.setModel(model);
            encounterJList.setSelectedIndex(0);
            try {
                openSelectedProfile();
            } catch (ParseException ex) {
                Logger.getLogger(DOCTOR_VIEW.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        peresonJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addressJLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        identifierJLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        zipCodeJLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cityJLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        stateJLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        communityNameJLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dobJLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mobileNoJLabel = new javax.swing.JLabel();
        encounterJPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        dateJLabel = new javax.swing.JLabel();
        jLabel_Hospital_Name = new javax.swing.JLabel();
        respiratoryRateJLabel = new javax.swing.JLabel();
        jLabel_Specialization = new javax.swing.JLabel();
        heartRateJLabel = new javax.swing.JLabel();
        ageJLabel = new javax.swing.JLabel();
        jLabel_Total_Experience = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        encounterJList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        uploadedJList = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Doctor Directory");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        peresonJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Name:");

        nameJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        nameJLabel.setText("Select Person to see details!");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Address:");

        addressJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        addressJLabel.setText("Select Person to see details!");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Enrollment Number");

        identifierJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        identifierJLabel.setText("Select Person to see details!");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Zip Code:");

        zipCodeJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        zipCodeJLabel.setText("Select Person to see details!");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("City:");

        cityJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cityJLabel.setText("Select Person to see details!");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("State:");

        stateJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        stateJLabel.setText("Select Person to see details!");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("Community Name:");

        communityNameJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        communityNameJLabel.setText("Select Person to see details!");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("DOB:");

        dobJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        dobJLabel.setText("Select Person to see details!");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Email ID:");

        emailJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        emailJLabel.setText("Select Person to see details!");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel11.setText("Mobile No.:");

        mobileNoJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        mobileNoJLabel.setText("Select Person to see details!");

        javax.swing.GroupLayout peresonJPanelLayout = new javax.swing.GroupLayout(peresonJPanel);
        peresonJPanel.setLayout(peresonJPanelLayout);
        peresonJPanelLayout.setHorizontalGroup(
            peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(peresonJPanelLayout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addGroup(peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nameJLabel)
                        .addComponent(addressJLabel)
                        .addComponent(identifierJLabel)
                        .addComponent(zipCodeJLabel)
                        .addComponent(cityJLabel)
                        .addComponent(stateJLabel)
                        .addComponent(communityNameJLabel)
                        .addComponent(emailJLabel)
                        .addComponent(dobJLabel)
                        .addComponent(mobileNoJLabel))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        peresonJPanelLayout.setVerticalGroup(
            peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
            .addGroup(peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(peresonJPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(identifierJLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(nameJLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(addressJLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(zipCodeJLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(cityJLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(stateJLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(communityNameJLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(dobJLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(emailJLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(peresonJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(mobileNoJLabel))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        encounterJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setText("Date:");

        dateJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        dateJLabel.setText("Select Person to see details!");

        jLabel_Hospital_Name.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_Hospital_Name.setText("Hospital Name");

        respiratoryRateJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        respiratoryRateJLabel.setText("Select Person to see details!");

        jLabel_Specialization.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_Specialization.setText("Specialization");

        heartRateJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        heartRateJLabel.setText("Select Person to see details!");

        ageJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ageJLabel.setText("Select Person to see details!");

        jLabel_Total_Experience.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_Total_Experience.setText("Total Experience");

        javax.swing.GroupLayout encounterJPanelLayout = new javax.swing.GroupLayout(encounterJPanel);
        encounterJPanel.setLayout(encounterJPanelLayout);
        encounterJPanelLayout.setHorizontalGroup(
            encounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encounterJPanelLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(encounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Hospital_Name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Specialization, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Total_Experience, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(encounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateJLabel)
                    .addComponent(respiratoryRateJLabel)
                    .addComponent(heartRateJLabel)
                    .addComponent(ageJLabel))
                .addGap(29, 29, 29))
        );
        encounterJPanelLayout.setVerticalGroup(
            encounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encounterJPanelLayout.createSequentialGroup()
                .addGroup(encounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(dateJLabel))
                .addGap(18, 18, 18)
                .addGroup(encounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Hospital_Name)
                    .addComponent(respiratoryRateJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(encounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Specialization)
                    .addComponent(heartRateJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(encounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Total_Experience)
                    .addComponent(ageJLabel))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(encounterJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(peresonJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peresonJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encounterJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Directory:");

        encounterJList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                encounterJListFocusGained(evt);
            }
        });
        encounterJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encounterJListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(encounterJList);

        uploadedJList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uploadedJListFocusGained(evt);
            }
        });
        uploadedJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadedJListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(uploadedJList);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Appointment");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSplitPane1)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void encounterJListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_encounterJListFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_encounterJListFocusGained

    private void encounterJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encounterJListMouseClicked
        openSelectedEncounter();
    }//GEN-LAST:event_encounterJListMouseClicked

    private void uploadedJListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uploadedJListFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_uploadedJListFocusGained

    private void uploadedJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadedJListMouseClicked
        try {
            openSelectedProfile();
        } catch (ParseException ex) {
            Logger.getLogger(DOCTOR_VIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_uploadedJListMouseClicked

   private void openSelectedEncounter() {
        int seletedPersonIndex = encounterJList.getSelectedIndex();
        if (seletedPersonIndex != -1) {
            Appointment history = selectedPerson.allAppointmentsHistory.AppointmentHistory.get(seletedPersonIndex);
            encounterJPanel.setVisible(true);
            jLabel12.setText(String.valueOf(history.visitDate));
            jLabel_Hospital_Name.setText(String.valueOf(history.findings.hospitalName));
            jLabel_Specialization.setText(String.valueOf(history.findings.specialization));
            jLabel_Total_Experience.setText(String.valueOf(history.findings.totalExperience));
        }
    }

    private void openSelectedProfile() throws ParseException {
        int seletedPersonIndex = uploadedJList.getSelectedIndex();
        if (seletedPersonIndex != -1) {
            selectedPerson = Doctor_Directory.doctorDirectory.get(seletedPersonIndex);
            identifierJLabel.setText(String.valueOf(selectedPerson.personDetails.personId));
            nameJLabel.setText(String.valueOf(selectedPerson.personDetails.name));
            addressJLabel.setText(String.valueOf(selectedPerson.personDetails.address));
            zipCodeJLabel.setText(String.valueOf(selectedPerson.personDetails.address.zipcode));
            cityJLabel.setText(String.valueOf(selectedPerson.personDetails.city.city));
            stateJLabel.setText(String.valueOf(selectedPerson.personDetails.city.state));
            communityNameJLabel.setText(String.valueOf(selectedPerson.personDetails.community.communityName));
            dobJLabel.setText((String.valueOf((new SimpleDateFormat("MM/dd/yyyy", Locale.US)).format(selectedPerson.personDetails.dob))));
            emailJLabel.setText(String.valueOf(selectedPerson.personDetails.email));
            mobileNoJLabel.setText(String.valueOf(selectedPerson.personDetails.mobileNo));

            DefaultListModel model = new DefaultListModel();
            selectedPerson.allAppointmentsHistory.AppointmentHistory.forEach(patient -> {
                model.addElement(patient.visitDate);
            });
            encounterJList.setModel(model);
            encounterJList.setSelectedIndex(0);

            encounterJList.setVisible(true);
            openSelectedEncounter();
//            isPatientJLabel.setText(String.valueOf(selectedPerson.type == 0 ? "No" : "Yes"));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressJLabel;
    private javax.swing.JLabel ageJLabel;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JLabel communityNameJLabel;
    private javax.swing.JLabel dateJLabel;
    private javax.swing.JLabel dobJLabel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JList<String> encounterJList;
    private javax.swing.JPanel encounterJPanel;
    private javax.swing.JLabel heartRateJLabel;
    private javax.swing.JLabel identifierJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Hospital_Name;
    private javax.swing.JLabel jLabel_Specialization;
    private javax.swing.JLabel jLabel_Total_Experience;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel mobileNoJLabel;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JPanel peresonJPanel;
    private javax.swing.JLabel respiratoryRateJLabel;
    private javax.swing.JLabel stateJLabel;
    private javax.swing.JList<String> uploadedJList;
    private javax.swing.JLabel zipCodeJLabel;
    // End of variables declaration//GEN-END:variables
}
