/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import Hospital_Management.Doctor;
import Hospital_Management.Doctor_Directory;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import Hospital_Management.System;
import static UI.Login_Page1.Main_JFrame;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
/**
 *
 * @author PRIYANSHI TANEJA
 */
public class Login_Page1 extends javax.swing.JFrame {

    
    /**
     * Creates new form Login_Page
     */
   // public Login_Page1

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Login_Button2 = new javax.swing.JButton();
        User_Name2 = new javax.swing.JTextField();
        Enter_Password2 = new javax.swing.JTextField();
        Logging_For2 = new javax.swing.JLabel();
        Choose2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel5.setText("Login");

        Login_Button2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Login_Button2.setForeground(new java.awt.Color(102, 153, 255));
        Login_Button2.setText("LOGIN");
        Login_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_Button2ActionPerformed(evt);
            }
        });

        User_Name2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        User_Name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_Name2ActionPerformed(evt);
            }
        });

        Enter_Password2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Logging_For2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Logging_For2.setText("Logging For");

        Choose2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Doctor", "Community Admin", "Patient", "Hospital Admin" }));
        Choose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel1.setText("Enter User ID");

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel2.setText("Enter Password");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_IMAGES/hospital-management-system.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(583, 583, 583)
                        .addComponent(Login_Button2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Enter_Password2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(Logging_For2))
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(186, 186, 186)
                                        .addComponent(Choose2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(User_Name2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 1009, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Logging_For2)
                            .addComponent(Choose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(User_Name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Enter_Password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Login_Button2)
                .addGap(152, 152, 152))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_Button2ActionPerformed
        String id = String.valueOf(Choose2.getSelectedItem());
        //String userName= enterUserName.getText();
        //String password= enterPassword.getText();

        /*if(userName.equalsIgnoreCase("System") && password.equalsIgnoreCase("Admin")){
            JOptionPane.showMessageDialog(this, "Login Successful");
        }
        else {
            JOptionPane.showMessageDialog(this, "Login Unsuccessful");      }*/

        if (Enter_Password2 != null && User_Name2 != null && Choose2.getSelectedItem().toString()=="Admin") {
            Boolean found = false;
            for (System admin : Main.adminLists) {
                if (admin.getPassword().equals(Enter_Password2.getText()) && admin.name.equals(User_Name2.getText())) {
                    found = true;
                    JOptionPane.showMessageDialog(this, "Admin logged in", "Login Successful", ERROR_MESSAGE);
                    //AdminDashboard adminDashboard = new AdminDashboard();
                    Left_Side adminOptions = new Left_Side(jSplitPane1, jPanel2, jPanel1);
                    //jSplitPane.setRightComponent(adminDashboard);
                    jSplitPane1.setLeftComponent(adminOptions);
                    ADD_COMMUNITY adminDashboard = new ADD_COMMUNITY();
                    jSplitPane1.setRightComponent(adminDashboard);
                    // LOGOUT_BUTTON.setVisible(true);
                }

            }
        }

        if (Enter_Password2 != null && User_Name2 != null && Choose2.getSelectedItem().toString()=="Hospital Admin") {
            Boolean found = false;
            for (System admin : Main.adminLists) {
                if (admin.getPassword().equals(Enter_Password2.getText()) && admin.name.equals(User_Name2.getText())) {
                    found = true;
                    JOptionPane.showMessageDialog(this, "Hospital Admin logged in", "Login Successful", ERROR_MESSAGE);
                    //AdminDashboard adminDashboard = new AdminDashboard();
                    Left_Side_Hospital adminOptions = new Left_Side_Hospital(jSplitPane1, jPanel2, jPanel1);
                    //jSplitPane.setRightComponent(adminDashboard);
                    jSplitPane1.setLeftComponent(adminOptions);
                    ADD_COMMUNITY adminDashboard = new ADD_COMMUNITY();
                    jSplitPane1.setRightComponent(adminDashboard);
                    // LOGOUT_BUTTON.setVisible(true);
                }

            }
        }
        if (Enter_Password2 != null && User_Name2 != null && Choose2.getSelectedItem().toString()=="Community Admin") {
            Boolean found = false;
            for (System admin : Main.adminLists) {
                if (admin.getPassword().equals(Enter_Password2.getText()) && admin.name.equals(User_Name2.getText())) {
                    found = true;
                    JOptionPane.showMessageDialog(this, "Community logged in", "Login Successful", ERROR_MESSAGE);
                    //AdminDashboard adminDashboard = new AdminDashboard();
                    Left_Side_Community_Admin adminOptions = new Left_Side_Community_Admin(jSplitPane1, jPanel2, jPanel1);
                    //jSplitPane.setRightComponent(adminDashboard);
                    jSplitPane1.setLeftComponent(adminOptions);
                    ADD_COMMUNITY adminDashboard = new ADD_COMMUNITY();
                    jSplitPane1.setRightComponent(adminDashboard);
                    //  LOGOUT_BUTTON.setVisible(true);
                }

            }

        }

        if (Enter_Password2 != null && User_Name2 != null && Choose2.getSelectedItem().toString()=="Patient") {
            Boolean found = false;
            for (System admin : Main.adminLists) {
                if (admin.getPassword().equals(Enter_Password2.getText()) && admin.name.equals(User_Name2.getText())) {
                    found = true;
                    JOptionPane.showMessageDialog(this, "Patient logged in", "Login Successful", ERROR_MESSAGE);
                    //AdminDashboard adminDashboard = new AdminDashboard();
                    Left_Side_Patient adminOptions = new Left_Side_Patient(jSplitPane1, jPanel2, jPanel1);
                    //jSplitPane.setRightComponent(adminDashboard);
                    jSplitPane1.setLeftComponent(adminOptions);
                    PATIENT_DIRECTORY patientViewEditDashbaord = new PATIENT_DIRECTORY();
                    jSplitPane1.setRightComponent(patientViewEditDashbaord);
                    // LOGOUT_BUTTON.setVisible(true);
                }

            }}
            if (Enter_Password2 != null && User_Name2 != null && Choose2.getSelectedItem().toString()=="Doctor") {
                Boolean found = false;
                for (System admin : Main.adminLists) {
                    if (admin.getPassword().equals(Enter_Password2.getText()) && admin.name.equals(User_Name2.getText())) {
                        found = true;
                        JOptionPane.showMessageDialog(this, "Doctor logged in", "Login Successful", ERROR_MESSAGE);
                        //AdminDashboard adminDashboard = new AdminDashboard();
                        Left_Side_Doctor adminOptions5 = new Left_Side_Doctor(jSplitPane1, jPanel2, jPanel1);
                        //jSplitPane.setRightComponent(adminDashboard);
                        jSplitPane1.setLeftComponent(adminOptions5);
                        ADD_PATIENT patientVisitDashbaord = new ADD_PATIENT();
                        jSplitPane1.setRightComponent(patientVisitDashbaord);
                        // LOGOUT_BUTTON.setVisible(true);
                    }

                }

                if (!found) {
                    JOptionPane.showMessageDialog(this, "Invalid Username or Password!", "Login", ERROR_MESSAGE);
                } /*else {
                    logoutJButton.setVisible(true);
                }*/
            } /*else {
                JOptionPane.showMessageDialog(this, "Username or Password requried.", "Login", ERROR_MESSAGE);
            } */

    }//GEN-LAST:event_Login_Button2ActionPerformed

    private void User_Name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_Name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_Name2ActionPerformed

    private void Choose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Choose2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main_JFrame(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     //   java.awt.EventQueue.invokeLater(new Runnable() {
      //      public void run() {
      //          new Login_Page().setVisible(true);
     //       }
       // });
        //</editor-fold>

        /* Create and display the form */
     //   java.awt.EventQueue.invokeLater(new Runnable() {
      //      public void run() {
      //          new Login_Page().setVisible(true);
     //       }
       // });
    }

    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel jPanel2;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Choose2;
    private javax.swing.JTextField Enter_Password2;
    private javax.swing.JLabel Logging_For2;
    private javax.swing.JButton Login_Button2;
    private javax.swing.JTextField User_Name2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
