/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import Hospital_Management.System;
import java.awt.Dimension;
import java.awt.Toolkit;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author SHREYA TANEJA
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public static ArrayList<System> adminLists = new ArrayList<System>();
    
    public Main() {
         parseJSON("\\Users\\PRIYANSHI TANEJA\\Desktop\\Assignment04\\src\\ui\\AuthenticationConfig.json");
        initComponents();
        LOGOUT_BUTTON.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
  private void parseJSON(String path) {
        JSONParser jsonParser = new JSONParser();
        try {
            Object obj = jsonParser.parse(new FileReader(path));
            JSONObject jsonObject = (JSONObject) obj;
            JSONObject adminList = (JSONObject) jsonObject.get("admin");
            Iterator<Object> adminIterator = adminList.keySet().iterator();
            int index = 1000;
            while (adminIterator.hasNext()) {
                Object key = adminIterator.next();
                Object value = (Object) adminList.get(key);
                JSONObject tempObject = (JSONObject) value;
                String tempEmail = (String) tempObject.get("email");
                String tempName = (String) tempObject.get("name");
                String tempPassword = (String) tempObject.get("password");
                System system = new System();
                system.email = tempEmail;
                system.name = tempName;
                system.setPassword(tempPassword);
                system.type = ("admin");
                system.identifier = index;
                adminLists.add(system);
                index++;
            }
            //System.out.println(String.valueOf(adminList));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (org.json.simple.parser.ParseException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Login_Button2 = new javax.swing.JButton();
        User_Name2 = new javax.swing.JTextField();
        Enter_Password2 = new javax.swing.JTextField();
        Logging_For2 = new javax.swing.JLabel();
        Choose2 = new javax.swing.JComboBox<>();
        LOGOUT_BUTTON = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel5.setText("Login");

        Login_Button2.setText("LOGIN");
        Login_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_Button2ActionPerformed(evt);
            }
        });

        User_Name2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        User_Name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_Name2ActionPerformed(evt);
            }
        });

        Enter_Password2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Logging_For2.setText("Logging For");

        Choose2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Admin", "Doctor", "Patient" }));
        Choose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose2ActionPerformed(evt);
            }
        });

        LOGOUT_BUTTON.setText("LOGOUT");
        LOGOUT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUT_BUTTONActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter User ID");

        jLabel2.setText("Enter Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LOGOUT_BUTTON)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Logging_For2)
                                .addGap(231, 231, 231)
                                .addComponent(Choose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Enter_Password2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(207, 207, 207)
                                    .addComponent(User_Name2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(Login_Button2)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel5)
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logging_For2)
                    .addComponent(Choose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User_Name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enter_Password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(61, 61, 61)
                .addComponent(Login_Button2)
                .addGap(96, 96, 96)
                .addComponent(LOGOUT_BUTTON)
                .addGap(17, 17, 17))
        );

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_Button2ActionPerformed
 String id = String.valueOf(Choose2.getSelectedItem());
        //String userName= enterUserName.getText();
        //String password= enterPassword.getText();
        
        /*if(userName.equalsIgnoreCase("System") && password.equalsIgnoreCase("Admin")){
           JOptionPane.showMessageDialog(this, "Login Successful");
        }
            else {
               JOptionPane.showMessageDialog(this, "Login Unsuccessful");      }*/
        
        if (Enter_Password2 != null && User_Name2 != null) {
            Boolean found = false;
            for (System admin : Main.adminLists) {
                if (admin.getPassword().equals(Enter_Password2.getText()) && admin.name.equals(User_Name2.getText())) {
                    found = true;
                    JOptionPane.showMessageDialog(this, "Admin logged in", "Login Successful", ERROR_MESSAGE);
                    //AdminDashboard adminDashboard = new AdminDashboard();
                    Left_Side adminOptions = new Left_Side(jSplitPane1, jPanel2, jPanel1);
                    //jSplitPane.setRightComponent(adminDashboard);
                   jSplitPane1.setLeftComponent(adminOptions);
                   
                   LOGOUT_BUTTON.setVisible(true);
                }
            }
            if (!found) {
                JOptionPane.showMessageDialog(this, "Invalid Username or Password!", "Login", ERROR_MESSAGE);
            } /*else {
                logoutJButton.setVisible(true);
            }*/
        } else {
            JOptionPane.showMessageDialog(this, "Username or Password requried.", "Login", ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_Login_Button2ActionPerformed

    private void User_Name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_Name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_Name2ActionPerformed

    private void Choose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Choose2ActionPerformed

    private void LOGOUT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUT_BUTTONActionPerformed
LOGOUT_BUTTON.setVisible(false);
        jSplitPane1.setRightComponent(jPanel1);
         jSplitPane1.setDividerLocation((int) (0 * (new Dimension(Toolkit.getDefaultToolkit().getScreenSize()).width)));        // TODO add your handling code here:
    }//GEN-LAST:event_LOGOUT_BUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Choose2;
    private javax.swing.JTextField Enter_Password2;
    private javax.swing.JButton LOGOUT_BUTTON;
    private javax.swing.JLabel Logging_For2;
    private javax.swing.JButton Login_Button2;
    private javax.swing.JTextField User_Name2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    
}
